#debug: true
auth0:
  audience: https://dev-qrj9gibi.us.auth0.com/api/v2/
kafka:
  topic:
    transaction: transaction


spring:
  application:
    name: synpulse
  security:
#    user:
#      password: Test12345_
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-qrj9gibi.us.auth0.com/

  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/cache
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
